site_name: My Docs
site_description: My documentation powered by MkDocs + Material on GitHub Pages
site_url: https://Jarvis03.github.io/blog_page/

nav:
  - Home: index.md
  - Guide:
      - Getting Started: guide/getting-started.md
  - Blog:
      - First Post: blog/first-post.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.share

repo_url: https://github.com/Jarvis03/blog_page/
repo_name: blog_page
edit_uri: ""

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jarvis03